### ISSUE TITLE
Add Nausicaa to "Alternative Telemachus Interfaces"

### ISSUE THREAD

**Issue by fixermark** [richardbunt/Telemachus#40]
Recommendation: Add the following to https://github.com/richardbunt/Telemachus/wiki/Alternative-Telemachus-Interfaces

Nausicaa [GitHub: https://github.com/fixermark/Nausicaa, Intro video: https://www.youtube.com/watch?v=mEFK3JnkHJE] - Google Glass telemetry dashboard

**Comment by richardbunt** [comment]
Awesome work! Added to the list :)
