### ISSUE TITLE
Faulty JSON received on websocket

### ISSUE THREAD

**Issue by phwoelfel** [richardbunt/Telemachus#48]
I wanted to use MKON with Telemachus today and found out that telemachus isn't sending correctly formatted JSON which causes MKON to malfunction (see also: https://github.com/chrisnic/mkon/issues/8)

The attribute name for the pod is missing in the JSON sent:
```
{:"Mark1-2Pod","v.name":1,"p.paused":"1.4.28.0"}
```

**Comment by richardbunt** [comment]
This looks like issue #35, which should have been fixed in the latest version of Telemachus. Which version are you using?

**Comment by phwoelfel** [comment]
I'm using the 1.4.29.0 version from KerbalStuff. I just checked my output_log.txt and noticed it says 1.4.28.0 (as well as in the JSON above) but I just started using telemachus and downloaded it yesterday. So it can't be an old installation mixed up. Maybe the version number wasn't changed or the zip on KS is not the right one?

**Comment by richardbunt** [comment]
Something is definitely broken here. The files on Kerbalstuff match the version that should be up there, so it is possible I made a mistake during the build process. I'll take a look when I get back to my development machine.

**Comment by richardbunt** [comment]
The wrong files were made available because I had the wrong start-up project selected in Visual Studio when I performed the build. 

Github, KerbalStuff and Curse have all been updated with the correct 1.4.29.0 files now.

**Comment by phwoelfel** [comment]
Thanks that fixed it!
